=== YuriLu/epam-java-lessons/src/by/epam/lw05/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tariffs">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="tariff">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:ID"/>
                            <xs:element name="title" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction>
                                        <xs:pattern value="[a-z 0-9]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="mobile"/>
                                        <xs:enumeration value="internet"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="started" type="xs:date"/>
                            <xs:element name="active" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== YuriLu/epam-java-lessons/src/by/epam/lw05/file.xml
<?xml version="1.0"?>
<tariffs
        xmlns="http://example.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com schema.xsd"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <tariff>
        <id>1</id>
        <title>WEB 500</title>
        <type>internet</type>
        <price>20000</price>
        <started>2014-01-30</started>
        <active>true</active>
    </tariff>
    <tariff>
        <id>2</id>
        <title>WEB 1000</title>
        <type>internet</type>
        <price>35000</price>
        <started>2014-01-03</started>
        <active>true</active>
    </tariff>
    <tariff>
        <id>3</id>
        <title>Privet</title>
        <type>mobile</type>
        <price>60000</price>
        <started>2014-06-15</started>
        <active>false</active>
    </tariff>
</tariffs>
